service: lambda-cicd

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

  status:
    handler: handler.status
    events:
      - http:
          path: status
          method: get

  time:
    handler: handler.time
    events:
      - http:
          path: time
          method: get